---
title: "git_01"
author: "Emann Malik"
date: "February 12, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
ALL in the golden afternoon  
Full leisurely we glide;  
For both our oars, with little skill,  
By little arms are plied,  
While little hands make vain pretence  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
Whose woods these are I think I know.     
His house is in the village though;     
He will not see me stopping here     
To watch his woods fill up with snow.     
  
My little horse must think it queer   
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,    
Because she thought the sun  
Had got no business to be there  
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
  
From childhood’s hour I have not been  
As others were—I have not seen  
As others saw—I could not bring  
My passions from a common spring—  
From the same source I have not taken  
My sorrow—I could not awaken  
My heart to joy at the same tone—  
And all I lov’d—I lov’d alone—  
  